### ISSUE TITLE
Add support to work with self signed SSL certificate

### ISSUE THREAD

**Issue by onlineapps-cloud** [btcpayserver/woocommerce-greenfield-plugin#28]
hi, i want to use btcpay server with self signed certificate, i don't have a domain to obtain a valid let's encrypt certificate.
i had these errors when i want to use on internal network (woocomerce and btcpay server):
![image](https://github.com/btcpayserver/woocommerce-greenfield-plugin/assets/69077240/a60eaa85-32c2-428a-94ee-82c8da3e6281)
![image](https://github.com/btcpayserver/woocommerce-greenfield-plugin/assets/69077240/3ab3d59e-4535-47b0-a891-74149b958047)
`this error i receive when i want to use setup wizard to generati API key, (i generated API manually)`
![image](https://github.com/btcpayserver/woocommerce-greenfield-plugin/assets/69077240/4c47f560-7fd9-402f-87c9-ac1df646b78b)
`it's possible to add checkbox in btcpay woocommerce plugin to use with self signed certificate for development purposes?`

**Comment by ndeet** [comment]
Hi, this is nothing that can be set by the WooCommerce plugin but that is done in the [PHP library](https://github.com/btcpayserver/btcpayserver-greenfield-php).

From top of my head you have a few options:
- on Mac or Linux use `mkcert` which will import certs to your OS and everything will work
- import your self signed cert to your operating system ssl store
- import self signed cert to cURL with option CURLOPT_CAINFO
- disable cURL SSL check with option CURLOPT_SSL_VERIFYPEER

The latter 2 options above can be set in the CurlClient class of the library found in the `vendor` directory of the WooCommerce plugin. You need to set the options [here](https://github.com/btcpayserver/btcpayserver-greenfield-php/blob/master/src/Http/CurlClient.php#L57) or implement your own client using ClientInterface so that it ignores SSL cert validation.
