### ISSUE TITLE
[Bug]: Sats-Mode in woocommerce btcpay server plugin causes critical error

### ISSUE THREAD

**Issue by postcashcash** [btcpayserver/woocommerce-greenfield-plugin#43]
### What is your BTCPay version?

BTCPay Server v1.12.5+a86165ac0

### How did you deploy BTCPay Server?

through lunanode.
but same issue with the demoserver from btcpay: mainnet.demo.btcpayserver.org

### What happened?

after selecting btcpay in checkout btcpayserver page didnt load but generic "sorry" statement appeard.
was able to extract related serverlog through woocommerce btcplay plugin frontend configuration setting "enable logs".
the log is
[fatal-errors-2024-03-16-515550f350757a8c003a6e3b41e47b07.log](https://github.com/btcpayserver/btcpayserver/files/14624355/fatal-errors-2024-03-16-515550f350757a8c003a6e3b41e47b07.log)

### How did you encounter this bug?

selected sats mode in wordpress plugin BTCPay For Woocommerce V2 in pluginsettings:
![buged_setting_btcpay_woocommerce](https://github.com/btcpayserver/btcpayserver/assets/163666707/077ccc27-8a69-449e-98e6-86fa9b79cb04)

### Relevant log output

```shell
out of file [fatal-errors-2024-03-16-515550f350757a8c003a6e3b41e47b07.log](https://github.com/btcpayserver/btcpayserver/files/14624355/fatal-errors-2024-03-16-515550f350757a8c003a6e3b41e47b07.log):
AbstractGateway.php:752:
// Handle Sats-mode.
		// Because BTCPay does not understand SAT as a currency we need to change to BTC and adjust the amount.
		if ($currency === 'SAT') {
			$currency = 'BTC';
752:>>>>>>>>>>>>>>>>>>> $amountBTC = bcdiv($amount->__toString(), '100000000', 8);
			$amount = PreciseNumber::parseString($amountBTC);
		}
```

### Additional information

likely irrelevant:  i also enabled sats as currency in woocommerce settings.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
Hi, thanks for your report!

The problem is that on the server you run your site on the [BCMath extension](https://www.php.net/manual/en/book.bc.php) is missing. If you control the webserver and it runs Debian/Ubuntu you can install it via `apt install php-bcmath`. For other distributions a quick search should help you find the needed package/command.

**Comment by BrianHenryIE** [comment]
I use [phpseclib/bcmath_compat](https://github.com/phpseclib/bcmath_compat) in [my Bitcoin gateway](https://github.com/BrianHenryIE/bh-wp-bitcoin-gateway/). Also managed to get away from needing GMP by using [nimiq/php-xpub](https://github.com/nimiq/php-xpub) (still have to push that change to GitHub).

**Comment by ndeet** [comment]
Hi @BrianHenryIE thanks for pointing out the polyfill for bcmath, did not know it existed. Will consider it but it seems to be rather common to have bcmath available 99% of the time. First user reporting this issue with 2000+ installs. Anyway, polyfill might be a good idea.

We do not generate addresses from xpub like you do with your plugin so that php-xpub or GMP is not needed.

**Comment by ndeet** [comment]
@postcashcash were you able to install bcmath extension and did it fix your problem?
